### ISSUE TITLE
camera position

### ISSUE THREAD

**Issue by markr307** [zdzhaoyong/Map2DFusion#10]
Hi, you have the calculated camera position shown in the demo video.  Is there a way to output (graphically or text) the camera position from the application?  I tried multiple settings for the Map2D.Type (1 through 4) but didn't see that version of the application display.  

thanks a lot!

**Comment by zdzhaoyong** [comment]
The camera position is computed with a slam algorithm which here does not contained. Please visit www.rtmapper.com and try RTMapper instead.
