### ISSUE TITLE
Impossible to compile

### ISSUE THREAD

**Issue by giovannicimolin** [zdzhaoyong/Map2DFusion#11]
I can't compile your software in any way.

How did you build yours?
Which system?
GCC version?
Opencv version?
Is there some code missing?

I get this error when I try to compile:

```c++
Map2DRender.cpp: In member function ‘virtual void Map2DFusion::MultiBandBlender::prepare(cv::Rect)’:
Map2DRender.cpp:87:31: error: no match for ‘operator=’ (operand types are ‘__gnu_cxx::__alloc_traits<std::allocator<cv::Mat> >::value_type {aka cv::Mat}’ and ‘cv::UMat’)
         dst_pyr_laplace_[0] = dst_;
```

And many others changing the system version and library versions...

**Comment by zdzhaoyong** [comment]
This error is caused since you are using OpenCV3, please use opencv 2.4 and qt4 instead.

**Comment by hededesedede** [comment]
@giovannicimolin I didn't complie from cmake for windows. can you help me and give me the code for visual studio or qt? please
