### ISSUE TITLE
the http://zhaoyong.adv-ci.com/ is a 404 error

### ISSUE THREAD

**Issue by city19992** [zdzhaoyong/Map2DFusion#25]
good job!
but I can not visit http://zhaoyong.adv-ci.com/. how can I download these datasets?

**Comment by zdzhaoyong** [comment]
website is down, please direct visit baiduyunpan with url: 
https://pan.baidu.com/s/1bW-4qtNzJzdQAo8QdOG-KA?pwd=vaxv

**Comment by city19992** [comment]
thank you very much for these datasets.
