### ISSUE TITLE
trajectory.txt

### ISSUE THREAD

**Issue by C8PAN** [zdzhaoyong/Map2DFusion#3]
I tried the sample sequence phantom3-village-kfs. The result is quite impressive.
This sequence comes with  a text file trajectory.txt. I am wondering how can I compute a similar trajectory.txt for my own sequence? In the trajectory.txt, It seems the eight values per line are timestamp, tx, ty, tz, w, rx, ry, rz.

**Comment by zdzhaoyong** [comment]
The trajectory is generated from a SLAM system, you can either use the ORB_SLAM to output the trajectory but the result is not usable directly and you need add some functions like plane fitting.
You can also fork our open source GSLAM(https://github.com/zdzhaoyong/GSLAM) and we are going to use Map2DFusion as a demo of GSLAM.

**Comment by C8PAN** [comment]
Thank you. excited to see the new demo.

**Comment by immuhammadadil** [comment]
Can you please elaborate the contents of trajectory file? What are the contents of columns?
