### ISSUE TITLE
core dumped issue

### ISSUE THREAD

**Issue by Ammarah-Farooq** [zdzhaoyong/Map2DFusion#5]
I am unable to solve core dumped issue. I am changing to Qt4 like this  qmake -qt=qt4 --version. then I run make file again. it executes. but main program again gives core dumped issue.

**Comment by zdzhaoyong** [comment]
Please make sure both opencv and qglviewer also use Qt4 instead of Qt5.

**Comment by immuhammadadil** [comment]
@Ammarah-Farooq did you successfully run map2DFusion?
