### ISSUE TITLE
trajectory.txt required or optional?

### ISSUE THREAD

**Issue by markr307** [zdzhaoyong/Map2DFusion#9]
Hi, is trajectory.txt required or optional to running Map2DFusion?  I tried removing the TrajectoryFile parameter from the config.cfg file in the phantom3-village-kfs dataset, and deleted the file itself, but the software still looks for the file and doesn't start without it.

Thanks a lot!!

**Comment by zdzhaoyong** [comment]
Yes the trajectory is enssentialed and if you want to output poses and mosaic from images directly please try RTMapper( www.rtmapper.com)

**Comment by immuhammadadil** [comment]
Hi,
I have a follow up question,
What are the camera parameters in the config?
Thanks
